# Generated by Django 6.1.1 on 2026-09-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('manage_room', 'Can manage rooms')],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=100)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_capacity', models.IntegerField()),
            ],
            options={
                'permissions': [('manage_room_type', 'Can manage room types')],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_assignments', to='staff.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_assignments', to='rooms.room')),
            ],
            options={
                'permissions': [('manage_housekeeping', 'Can manage housekeeping assignments')],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype'),
        ),
    ]
