# Generated by Django 6.1.1 on 2026-09-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housekeeping_assignments', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('room_number__regex', '^[A-Z0-9][A-Z0-9 -]*$')), name='room_number_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('room_capacity__gte', 1)), name='room_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('room_price__gt', 0)), name='room_price_positive'),
        ),
    ]
