# Generated by Django 6.1.1 on 2026-09-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_housekeepingassignment_room_and_more'),
        ('staff', '0002_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='housekeepingassignment',
            constraint=models.UniqueConstraint(fields=('room', 'assigned_to', 'assignment_date'), name='unique_housekeeping_room_staff_date'),
        ),
    ]
