# Generated by Django 6.1.1 on 2026-09-25 07:29

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_enable_btree_gist'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'canceled'), _negated=True), expressions=[('room', '='), (models.Func(models.F('check_in_date'), models.F('check_out_date'), function='daterange'), '&&')], name='prevent_overlapping_bookings'),
        ),
    ]
