# Generated by Django 6.1.1 on 2026-09-28 07:54

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_prevent_overlapping_bookings'),
        ('rooms', '0002_alter_housekeepingassignment_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='prevent_overlapping_bookings',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_guests__gte', 1)), name='booking_guest_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_in_date__lt', models.F('check_out_date'))), name='booking_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['canceled', 'checked_out']), _negated=True), expressions=[('room', '='), (models.Func(models.F('check_in_date'), models.F('check_out_date'), function='daterange'), '&&')], name='prevent_overlapping_bookings'),
        ),
    ]
